logging_level: INFO

results_dir: 'results/'
run: 'run_10_weather_years'

model:
  nodes: "37"
  tres: "3"
  co2: "0"
  sectors: "T-H-B-I-A"

scenario:
  design_year: 
  - 2013
  weather_year:
  # - 1960
  # - 1961
  # - 1962
  # - 1963
  # - 1964
  # - 1965
  # - 1966
  # - 1967
  # - 1968
  # - 1969
  # - 1970
  # - 1971
  # - 1972
  # - 1973
  # - 1974
  # - 1975
  # - 1976
  # - 1977
  # - 1978
  # - 1979
  # - 1980
  # - 1981
  # - 1982
  # - 1983
  # - 1984
  # - 1985
  # - 1986
  # - 1987
  # - 1988
  # - 1989
  # - 1990
  # - 1991
  # - 1992
  # - 1993
  # - 1994
  # - 1995
  # - 1996
  # - 1997
  # - 1998
  # - 1999
  # - 2000
  # - 2001
  # - 2002
  # - 2003
  - 2004
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  - 2010
  - 2011
  - 2012
  - 2013
  # - 2014
  # - 2015
  # - 2016
  # - 2017
  # - 2018
  # - 2019
  # - 2020
  # - 2021


  generators_extendable: False
  links_extendable: False
  stores_extendable: False
  
  add_co2_price: True
  custom_co2_price: False
  co2_price: 500 # EUR/tCO2 (Only used if 'custom_co2_price' is set to True and 'add_co2_price' is also True)
  
  add_co2_lim: False
  new_co2_lim: 0.05 # global co2 emissions constraint in percentage relative to 1990-levels
  
  hydroconstrained: False

solving:
  mem: 25000