logging_level: INFO

results_dir: 'results/'
run: 'run_3hours'

model:
  nodes: "37"
  tres: "3"
  co2: "0"
  sectors: "T-H-B-I-A"

scenario:
  design_year: 
  - 2013
  weather_year:
  - 2001
  - 2013

  generators_extendable: False
  links_extendable: False 
  stores_extendable: False
  add_co2_price: False 
  hydroconstrained: False

solving:
  mem: 100000