logging_level: INFO

results_dir: 'results/'
run: 'run_3hour_20years'

model:
  nodes: "37"
  tres: "3"
  co2: "0"
  sectors: "T-H-B-I-A"

scenario:
  design_year: 
  - 2013
  weather_year:
  - 2000
  - 2001
  - 2002
  - 2003
  - 2004
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  - 2010
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019

  generators_extendable: False # True # False
  links_extendable: False 
  stores_extendable: False # True #False
  add_co2_price: True
  hydroconstrained: False

solving:
  mem: 100000