logging_level: INFO

results_dir: 'results/'
run: 'sensitivity_transmission_dy1968'

# Model specifications of the design model
model: 
  nodes: "37" # number of nodes
  tres: "3" # temporal resolution
  co2: "0" # co2 limit relative to 1990
  sectors: "T-H-B-I-A" 
# Ideally, this should refer to the PyPSA-Eur workflow as, if changed, we would need to run a new design scenario. 
# Currently, this is not the case, and, thus, requires the user to already have the design scenario available.

scenario:
  design_year:
  - 1960
  - 1961
  - 1962
  - 1963
  - 1964
  - 1965
  - 1966
  - 1967
  - 1968
  - 1969
  - 1970
  - 1971
  - 1972
  - 1973
  - 1974
  - 1975
  - 1976
  - 1977
  - 1978
  - 1979
  - 1980
  - 1981
  - 1982
  - 1983
  - 1984
  - 1985
  - 1986
  - 1987
  - 1988
  - 1989
  - 1990
  - 1991
  - 1992
  - 1993
  - 1994
  - 1995
  - 1996
  - 1997
  - 1998
  - 1999
  - 2000
  - 2001
  - 2002
  - 2003
  - 2004
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  - 2010
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021
  weather_year:
  - 1960
  - 1961
  - 1962
  - 1963
  - 1964
  - 1965
  - 1966
  - 1967
  - 1968
  - 1969
  - 1970
  - 1971
  - 1972
  - 1973
  - 1974
  - 1975
  - 1976
  - 1977
  - 1978
  - 1979
  - 1980
  - 1981
  - 1982
  - 1983
  - 1984
  - 1985
  - 1986
  - 1987
  - 1988
  - 1989
  - 1990
  - 1991
  - 1992
  - 1993
  - 1994
  - 1995
  - 1996
  - 1997
  - 1998
  - 1999
  - 2000
  - 2001
  - 2002
  - 2003
  - 2004
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  - 2010
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021

  opts:
    - hydro-solar-wind-heat # full model
    # Define here the variable that should be dependent on the model weather year ("hydro", "solar", "wind", "heat"). 
    # If not included, the variable will be calculated based on the design year (2013).

  lvl: # transmission level
    # - 1.1
    - 1.3
    - 1.5
    - 1.7
    - 2.0
    - opt

  # Fix capacities (set the extension of the following components to "False")
  generators_extendable: False # False = fixed capacity, True = the model can choose to build more 
  links_extendable: False
  stores_extendable: False
  
  # Split model horizon (from summer to summer instead of winter to winter)
  split_horizon: False

  # CO2 emissions settings
  add_co2_price: True # Add CO2 emissions price
  custom_co2_price: False # Add CO2 price exogenously (If False, then CO2 price is based on the lagrange multiplier 
                          # of the CO2 emissions constraint in the capacity optimization)
  co2_price: 500 # CO2 emissions price in EUR/tCO2 (Only active if 'custom_co2_price' is True)
  add_co2_lim: False # Add CO2 emissions limit (Only active if "add_co2_price" is False)
  new_co2_lim: 0.05 # global co2 emissions constraint in percentage relative to 1990-levels (Only active if 'add_co2_lim' is set to True)
  
  # Add seasonal limit on hydropower to resemble limited foresight
  hydroconstrained: True # If True, hydropower is constrained by its SOC to stay within [5%,95%] quantiles of historical data

solving:
  mem: 20000 # memory allocated in solving the dispatch optimization